#!/bin/bash

# Navigate to the frontend directory
cd frontend

# Run linting and formatting checks
npx prettier --check --config .prettierrc "**/*.{js,jsx,ts,tsx,css,json,mjs,cjs,yml,yaml}" --ignore-path .gitignore --ignore-path .prettierignore
npx next lint

# Check the exit status of the commands
if [ $? -ne 0 ]; then
  echo "Linting or formatting failed. Please fix the issues before pushing."
  exit 1
fi