FROM node:20.16.0-alpine AS deps

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

FROM node:20.16.0-alpine AS builder

WORKDIR /app

COPY . .

RUN rm -rf node_modules

COPY --from=deps /app/node_modules ./node_modules

FROM node:20.16.0-alpine AS runner

WORKDIR /app

# Copy only the necessary files from the builder stage
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/tsconfig.json ./tsconfig.json
COPY --from=builder /app/tsconfig.paths.json ./tsconfig.paths.json
COPY --from=builder /app/components.json ./components.json
COPY --from=builder /app/next-env.d.ts ./next-env.d.ts
COPY --from=builder /app/tailwind.config.ts ./tailwind.config.ts
COPY --from=builder /app/postcss.config.mjs ./postcss.config.mjs
COPY --from=builder /app/app ./app
COPY --from=builder /app/public ./public
COPY --from=builder /app/components ./components
COPY --from=builder /app/features ./features
COPY --from=builder /app/hooks ./hooks
COPY --from=builder /app/lib ./lib
COPY --from=builder /app/node_modules ./node_modules

CMD ["node_modules/.bin/next", "dev", "--port", "4000"]
