FROM node:20.16.0-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

ENV PORT=3000
EXPOSE 3000

CMD ["pnpm", "run", "dev"]
